# Generated by Django 4.0.2 on 2022-02-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peoples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('sename', models.CharField(blank=True, max_length=50, verbose_name='Отчество')),
                ('familia', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('female', models.CharField(choices=[('мужской', 'муж'), ('женский', 'жен')], default='муж', max_length=10, verbose_name='Пол')),
                ('dateOfBirth', models.DateField(verbose_name='Дата рождения')),
                ('dateStartWork', models.DateField(verbose_name='Дата приема на работу')),
                ('dateFinishtWork', models.DateField(verbose_name='Дата увольнения')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания записи')),
                ('modify_at', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования записи')),
                ('photo', models.ImageField(height_field=200, upload_to='photos/%Y%m%d/', verbose_name='Фото', width_field=200)),
            ],
        ),
    ]
